jenkins:
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - assignments:
          - "faranguren@adlcorpsandboxoutlook.onmicrosoft.com"
          - "johan@adlcorpsandboxoutlook.onmicrosoft.com"
          - "jeforp_906@hotmail.com"
          - "lcuellar@adlcorpsandboxoutlook.onmicrosoft.com"
          - "adlcorpsandbox@outlook.com"
          - "said.fayad@adlcorpsandboxoutlook.onmicrosoft.com"
          - "said.fad@adlcorpsandboxoutlook.onmicrosoft.com"
          - "david.dager@adlcorpsandboxoutlook.onmicrosoft.com"
          - "juan.montero@adlcorpsandboxoutlook.onmicrosoft.com"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Job/Move"
          - "Job/Build"
          - "Lockable Resources/View"
          - "Credentials/Delete"
          - "Credentials/ManageDomains"
          - "Lockable Resources/Unlock"
          - "View/Create"
          - "Agent/Configure"
          - "Job/Read"
          - "Credentials/Update"
          - "Agent/Create"
          - "Job/Delete"
          - "Agent/Build"
          - "View/Configure"
          - "Metrics/HealthCheck"
          - "Lockable Resources/Reserve"
          - "Agent/Provision"
          - "Metrics/ThreadDump"
          - "SCM/Tag"
          - "Job/Create"
          - "Job/Discover"
          - "Agent/ExtendedRead"
          - "Credentials/View"
          - "Agent/Connect"
          - "Agent/Delete"
          - "Run/Replay"
          - "Agent/Disconnect"
          - "Run/Delete"
          - "Job/Cancel"
          - "Overall/Read"
          - "Run/Update"
          - "Credentials/Create"
          - "Overall/Administer"
          - "View/Delete"
          - "Job/Configure"
          - "Metrics/View"
          - "Job/Workspace"
          - "View/Read"
        - assignments:
          - "all-execution-groups"
          name: "execution"
          pattern: ".*"
          permissions:
          - "Job/Cancel"
          - "Overall/Read"
          - "Job/Build"
          - "Job/Read"
        - assignments:
          - "readers-groups"
          name: "readers"
          pattern: ".*"
          permissions:
          - "Overall/Read"
        items:
        - assignments:
          - "custom-execution-groups"
          name: "custom-permissions"
          pattern: "^ath-.*"
          permissions:
          - "Job/Cancel"
          - "Job/Build"
          - "Job/Read"
