---

  - name: Upgrade all packages for RedHat or Amazon Linux.
    yum:
      name: "*"
      state: latest
  
  - name: Install a list of packages.
    yum:
      name: 
        - wget
        - unzip
        - java-1.8.0-openjdk
      state: present

...
  